package org.example.mapper;

import org.example.dto.category.CategoryCreateDTO;
import org.example.model.CategoryEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings;
import org.mapstruct.Named;
import org.springframework.web.multipart.MultipartFile;

@Mapper(componentModel = "spring")
public interface CategoryMapper {

    @Mappings({
            @Mapping(source = "image", target = "image", qualifiedByName = "mapMultipartFileToString"),
            @Mapping(target = "id", ignore = true), // id is generated by the database
            @Mapping(target = "creationTime", ignore = true) // creationTime is set manually
    })
    CategoryEntity categoryEntityByCategoryCreateDTO(CategoryCreateDTO category);

    @Mappings({
            @Mapping(target = "image", ignore = true) // No reverse mapping from String to MultipartFile
    })
    CategoryCreateDTO categoryCreateDTOByCategoryEntity(CategoryEntity category);

    @Named("mapMultipartFileToString")
    default String mapMultipartFileToString(MultipartFile file) {
        return file != null ? file.getOriginalFilename() : null;
    }
}
